name: feur
description: A cool manga reader and downloader
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto_Slab
      fonts:
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Regular.ttf
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Slab/RobotoSlab-Light.ttf
          weight: 300
    - family : Roboto_Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
        

