name : Build projet and release as zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive production artifact
        uses: actions/upload-artifact@v2
        run: |
          zip -r release.zip dist assets manifest.json
          mv release.zip $GITHUB_WORKSPACE
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download production artifact
        uses: actions/download-artifact@v2
        with:
          name: release
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release.zip
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: |
            Release ${{ github.sha }}
          draft: false
          prerelease: false

        